### ISSUE TITLE
Example shows the role to call as aws-ec2-provisioning for the ansible-aws-asg role

### ISSUE THREAD

**Issue by efreedom79** [VivaReal/ansible-aws-asg#1]
Should it call aws-asg rather than naws-ec2-provisioning?

Also, there is a launch configuration variable. Should I set up Launch configuration first and then call this OR can I use the ec2 provisioning names and it handles converting it over to the launch configuration?

I'm getting an error:

TASK [VivaReal.aws-lc : create launch config] **********************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "BotoServerError: 400 Bad Request\n<ErrorResponse xmlns=\"http://autoscaling.amazonaws.com/doc/2011-01-01/\">\n  <Error>\n    <Type>Sender</Type>\n    <Code>ValidationError</Code>\n    <Message>You are not authorized to perform this operation.</Message>\n  </Error>\n  <RequestId>10af7c6b-0721-11e6-ac54-9b05477c1cbb</RequestId>\n</ErrorResponse>\n"}

And it doesn't seem to matter if I use the arn profile name, arn role name or just the role name itself.

Bob

**Comment by gianrubio** [comment]
@efreedom79 sorry about the name, at now it's not possible to change.

I have created a sample project that can help you to setup your environment
https://github.com/gianrubio/immutable-infrastructure

If isn't sufficient, please put your playbook and your variables here.

**Comment by efreedom79** [comment]
So, working better now. Still running into a problem with the elb.

TASK [VivaReal.aws-lc : set fact aws_lc] ***************************************
task path: /home/vagrant/GIT/iac/ansible/galaxy-roles/VivaReal.aws-lc/tasks/main.yml:28
ok: [localhost] => {"ansible_facts": {"ec2_launch_config_name": "devops-ldapServer-prd-LC"}, "changed": false, "invocation": {"module_args": {"ec2_launch_config
_name": "devops-ldapServer-prd-LC"}, "module_name": "set_fact"}}

TASK [VivaReal.aws-elb : fail] *************************************************
task path: /home/vagrant/GIT/iac/ansible/galaxy-roles/VivaReal.aws-elb/tasks/main.yml:3
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [VivaReal.aws-elb : create elb] *******************************************
task path: /home/vagrant/GIT/iac/ansible/galaxy-roles/VivaReal.aws-elb/tasks/main.yml:6
ESTABLISH LOCAL CONNECTION FOR USER: vagrant
127.0.0.1 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1461258676.03-251348245184612 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1461258676.03-251348245184612 `" )'
127.0.0.1 PUT /tmp/tmp_pMMam TO /home/vagrant/.ansible/tmp/ansible-tmp-1461258676.03-251348245184612/ec2_elb_lb
127.0.0.1 EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1461258676.03-2513\
48245184612/ec2_elb_lb; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1461258676.03-251348245184612/" > /dev/null 2>&1'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1461258676.03-251348245184612/ec2_elb_lb", line 3183, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1461258676.03-251348245184612/ec2_elb_lb", line 985, in main
    elb_man.ensure_ok()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1461258676.03-251348245184612/ec2_elb_lb", line 360, in ensure_ok
    self._create_elb()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1461258676.03-251348245184612/ec2_elb_lb", line 507, in _create_elb
    listeners = [self._listener_as_tuple(l) for l in self.listeners]
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1461258676.03-251348245184612/ec2_elb_lb", line 602, in _listener_as_tuple
    int(listener['load_balancer_port']),
TypeError: string indices must be integers, not str
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "ec2_elb_lb"}, "parsed": false}

My playbook looks like this

- hosts: localhost
  vars:
    region: us-west-2

    project_build: devops-ldapServer-prd
    aws_resource_tags: {
     'Name': 'devops-ldapServer-prd',
     'Team': 'devops',
     'App': 'ldapServer',
     'Env': 'prd',
     'Owner': 'devops',
    }

    state: present

    ec2_sg_id: ['sg-bc0b2adb', 'sg-0906276e']
    ec2_vpc_id: vpc-633dea07
    ec2_asg_subnets: ['subnet-ec6368b5', 'subnet-0879a66c', 'subnet-e846b69e']
    ec2_key_name: devops
    ec2_assign_public_ip: no
    ec2_instance_type: t2.medium
    ec2_instance_profile_name: 'basic'
    ec2_ami_image_id: ami-b0a051d0
    ec2_count: 1
    ec2_launch_config_name: "{{ aws_resource_tags['Name'] }}-LC"

    aws_elb_subnets: ['subnet-ec6368b5', 'subnet-0879a66c', 'subnet-e846b69e']
    aws_elb_scheme: 'internal'
    aws_elb_security_group_ids: ['sg-0906276e']
    aws_elb_instance_listeners: [636]
    aws_elb_ping_protocol: tcp
    aws_elb_ping_port: 636
    aws_elb_cross_az_load_balancing: yes

    aws_asg_desired_capacity: 1
    aws_asg_min_size: 1
    aws_asg_max_size: 1

    wait_for_instances: True

  roles:
    - role: VivaReal.aws-lc
    - role: VivaReal.aws-elb
    - role: VivaReal.aws-asg

**Comment by gianrubio** [comment]
@efreedom79 I'm happy that you are using our playbook :)

Both variable aws_elb_instance_listeners and project_build are wrong. Look at the default var for aws_elb_instance_listeners https://github.com/VivaReal/ansible-aws-elb/blob/master/defaults/main.yml
and rename project_build to vivareal_project_build. In the next version I will remove all vivarea_l prefix.

**Comment by gianrubio** [comment]
@efreedom79 Can I close this issue?
