### ISSUE TITLE
"Interval" variable on asg.yml defining different ansible module parameter

### ISSUE THREAD

**Issue by arioneto** [VivaReal/ansible-aws-asg#3]
Is that correct? (asg.yml)

    period: "{{ interval | default(300) }}"
    evaluation_periods: "{{ interval | default(3) }}"

Shouldn't be better using different variables?

**Comment by gianrubio** [comment]
@arioneto can you fix this?

change
evaluation_periods: "{{ interval | default(3) }}"
to 
evaluation_periods: "{{   aws_asg_evaluation_periods | default}}"

**Comment by arioneto** [comment]
ok
